version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules
    restart: always

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
